import React from 'react';
import Network_img from "../../assets/india-map-polygonal-mosaic-lines-rays-dots-vector-illustration-95328071.webp"
import './Networks.css';

const Networks = () => {
  return (
    <div id="network" className="networks-container" >
      <div className='text-left'>
        <h3>Data Integration</h3>
        <p>Power BI allows you to integrate data from various sources seamlessly. By interconnecting infrastructures, you can bring together data from different systems such as energy management systems, transportation systems, and financial systems, providing a comprehensive view of your operations.</p>
        <button className="btn">Read Article</button>
        <br />
        <br />
        <br />
        <br />
        <br />
        <h3>Real-time Monitoring</h3>
        <p>With Power BI's real-time data capabilities, you can monitor interconnected infrastructures in real-time. This enables quick decision-making and proactive problem-solving by identifying issues as they arise.</p>
        <button className="btn">Read Article</button>
      </div>
      <div className="circle">
        <img src={Network_img} alt="Network" className="network-image" />
      </div>
      <div className='text-right'>
        <h3>Scalability</h3>
        <p>Power BI is highly scalable, allowing you to handle large volumes of data generated by interconnected infrastructures. Whether you're monitoring a single facility or an entire network of infrastructures, Power BI can scale to meet your needs.</p>
        <button className="btn">Read Article</button>
        <br />
        <br />
        <br />
        <br />
        <br />
        <h3>Collaboration</h3>
        <p>Power BI enables collaboration by allowing multiple users to access and interact with data visualizations. This fosters collaboration among stakeholders involved in managing interconnected infrastructures, ensuring that everyone is aligned and informed.</p>
        <button className="btn">Read Article</button>
      </div>
    </div>
  );
};

export default Networks;

